### ISSUE TITLE
docker-compose up fails

### ISSUE THREAD

**Issue by cdrage** [fabric8io/fabric8-planner#88]
Looks like it's from the renaming of Dockerfile:

```
dropbox/dev/almighty-ui  master ✔                                                                                                                                                                                                                                            5d  
▶ docker-compose up 
Creating network "almightyui_default" with the default driver
Pulling db (centos/postgresql-95-centos7:latest)...
latest: Pulling from centos/postgresql-95-centos7
3d8673bd162a: Already exists
a3ed95caeb02: Pull complete
5c79d4aadf0c: Pull complete
69056b94959f: Pull complete
Digest: sha256:f76760462eba4e1f7f88d5868ccf9ae4ea39d201042d451063bf5848f32afbe7
Status: Downloaded newer image for centos/postgresql-95-centos7:latest
Creating almightyui_db_1
Pulling core (almightycore/almighty-core:latest)...
latest: Pulling from almightycore/almighty-core
3d8673bd162a: Already exists
219d25306236: Pull complete
1535dcaab3de: Pull complete
Digest: sha256:c8134e550dfe9872e68cb2bfc9332cb7bf4a80be4c439cc9bc013d565ae8a490
Status: Downloaded newer image for almightycore/almighty-core:latest
Creating almightyui_core_1
Building ui
ERROR: Cannot locate specified Dockerfile: Dockerfile
```

**Comment by cdrage** [comment]
Seems that specifying `Dockerfile.builder` within the compose file doesn't work either: 
```
version: '2'                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                  
services:                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                  
  core:                                                                                                                                                                                                                                                                           
    image: almightycore/almighty-core:latest                                                                                                                                                                                                                                      
    command: -dbhost db                                                                                                                                                                                                                                                           
    ports:                                                                                                                                                                                                                                                                        
      - "8080:8080"                                                                                                                                                                                                                                                               
    depends_on:                                                                                                                                                                                                                                                                   
      - db                                                                                                                                                                                                                                                                        
    networks:                                                                                                                                                                                                                                                                     
      - default                                                                                                                                                                                                                                                                   
  ui:                                                                                                                                                                                                                                                                             
    build:                                                                                                                                                                                                                                                                        
      context: .                                                                                                                                                                                                                                                                  
      dockerfile: Dockerfile.builder                                                                                                                                                                                                                                              
    entrypoint:                                                                                                                                                                                                                                                                   
      - /usr/local/bin/wait-for-it.sh                                                                                                                                                                                                                                             
      - core:8080                                                                                                                                                                                                                                                                 
      - --                                                                                                                                                                                                                                                                        
      - npm                                                                                                                                                                                                                                                                       
      - start                                                                                                                                                                                                                                                                     
    ports:                                                                                                                                                                                                                                                                        
      # TODO: Currently it only works if the UI port                                                                                                                                                                                                                              
      # is opened on the host as well.                                                                                                                                                                                                                                            
      - "8088:8088"                                                                                                                                                                                                                                                               
    environment:                                                                                                                                                                                                                                                                  
      API_URL: http://core:8080/api/                                                                                                                                                                                                                                              
    depends_on:                                                                                                                                                                                                                                                                   
      - core                                                                                                                                                                                                                                                                      
    networks:                                                                                                                                                                                                                                                                     
      - default                                                                                                                                                                                                                                                                   
  db:                                                                                                                                                                                                                                                                             
    image: centos/postgresql-95-centos7                                                                                                                                                                                                                                           
    ports:                                                                                                                                                                                                                                                                        
      - "5432"                                                                                                                                                                                                                                                                    
    environment:                                                                                                                                                                                                                                                                  
      POSTGRESQL_ADMIN_PASSWORD: mysecretpassword                                                                                                                                                                                                                                 
    networks:                                                                                                                                                                                                                                                                     
      - default            
```

Error:
```
dropbox/dev/almighty-ui  master ✗                                                                                                                                                                                                                                         6d ⚑  ⍉
▶ docker-compose up 
Creating network "almightyui_default" with the default driver
Creating almightyui_db_1
Creating almightyui_core_1
Creating almightyui_ui_1
ERROR: oci runtime error: exec: "/usr/local/bin/wait-for-it.sh": stat /usr/local/bin/wait-for-it.sh: no such file or directory
```
